CarsApp/Models/Car.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace CarsApp.Models
{
    public class Car
    {
        [Required]
        public int Id { get; set; }

        [Required]
        [StringLength(40)]
        [Display(Name = "Model")]
        public string Name { get; set; }

        [Range(1900, 2030)]
        [Display(Name = "Model Year")]
        public int? ModelYear { get; set; }

        [StringLength(40)]
        [Display(Name = "Chassis Type")]
        public string? Type { get; set; }

        [Display(Name = "Car Picture")]
        public string? CarPicture { get; set; }

        [Display(Name = "Manufacturer")]
        public int ManufacturerId { get; set; }

        [Display(Name = "Manufacturer")]
        [ForeignKey("ManufacturerId")]
        public Manufacturer Manufacturer { get; set; }

        public ICollection<Review> Reviews { get; set; }
    }
}

CarsApp/Controllers/DriversController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CarsApp.Data;
using CarsApp.Models;
using Microsoft.AspNetCore.Hosting;
using CarsApp.ViewModels;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace CarsApp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DriversController : Controller
    {
        private readonly CarsAppContext _context;
        private readonly IHostingEnvironment webHostingEnvironment;

        public DriversController(CarsAppContext context, IHostingEnvironment hostingEnvironment)
        {
            _context = context;
            webHostingEnvironment = hostingEnvironment;
        }

        // GET: Drivers
        public async Task<IActionResult> Index()
        {
            var carsAppContext = _context.Driver.Include(d => d.Reviews).ThenInclude(r => r.Car);
            return View(await _context.Driver.ToListAsync());
        }

        // GET: Drivers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var driver = await _context.Driver
                .Include(d => d.Reviews)
                .ThenInclude(r => r.Car)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.Id == id);

            if (driver == null)
            {
                return NotFound();
            }

            return View(driver);
        }

        // GET: Drivers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Drivers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(DriverViewModel model)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = UploadedFile(model);

                Driver driver = new Driver
                {
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    LicenceSince = model.LicenceSince,
                    DriverPicture = uniqueFileName
                };


                _context.Add(driver);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        // GET: Drivers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var driver = await _context.Driver.FindAsync(id);
            if (driver == null)
            {
                return NotFound();
            }
            return View(driver);
        }

        // POST: Drivers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, IFormFile imageUrl, [Bind("Id,FirstName,LastName,LicenceSince,DriverPicture")] Driver driver)
        {
            if (id != driver.Id)
            {
                return NotFound();
            }

            DriversController uploadImage = new DriversController(_context, webHostingEnvironment);
            driver.DriverPicture = uploadImage.UploadedFile(imageUrl);

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(driver);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DriverExists(driver.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(driver);
        }

        // GET: Drivers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var driver = await _context.Driver
                .FirstOrDefaultAsync(m => m.Id == id);
            if (driver == null)
            {
                return NotFound();
            }

            return View(driver);
        }

        // POST: Drivers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var driver = await _context.Driver.FindAsync(id);
            _context.Driver.Remove(driver);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DriverExists(int id)
        {
            return _context.Driver.Any(e => e.Id == id);
        }



        private string UploadedFile(DriverViewModel model)
        {
            string uniqueFileName = null;

            if (model.DriverPicture != null)
            {
                string uploadsFolder = Path.Combine(webHostingEnvironment.WebRootPath, "DriverImages");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + Path.GetFileName(model.DriverPicture.FileName);
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.DriverPicture.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }
        //Overloaded function UploadedFile for Edit
        public string UploadedFile(IFormFile file)
        {
            string uniqueFileName = null;
            if (file != null)
            {
                string uploadsFolder = Path.Combine(webHostingEnvironment.WebRootPath, "DriverImages");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + Path.GetFileName(file.FileName);
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    file.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }

    }
}

CarsApp/Controllers/GuestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CarsApp.Data;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CarsApp.Controllers
{
    public class GuestController : Controller
    {

        private readonly CarsAppContext _context;
        private readonly IHostingEnvironment webHostingEnvironment;

        public GuestController(CarsAppContext context, IHostingEnvironment hostingEnvironment)
        {
            _context = context;
            webHostingEnvironment = hostingEnvironment;
        }


        public IActionResult Index()
        {
            return View();
        }

        // GET: Guest/Manufacturers
        public async Task<IActionResult> Manufacturers(string sortOrder, string searchString)
        {
            ViewData["CountrySortParm"] = String.IsNullOrEmpty(sortOrder) ? "type_desc" : "";
            ViewData["CurrentFilter"] = searchString;
            var manufacturers = from m in _context.Manufacturer select m;
            manufacturers = manufacturers.Include(m => m.Cars);

            if (!String.IsNullOrEmpty(searchString))
            {
                manufacturers = manufacturers.Where(m => m.Name.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "type_desc":
                    manufacturers = manufacturers.OrderBy(m => m.Country);
                    break;
                default:
                    manufacturers = manufacturers.OrderBy(m => m.Name);
                    break;
            }

            return View(await manufacturers.AsNoTracking().ToListAsync());
        }


        // GET: Guest/ManufacturerDetails/5
        public async Task<IActionResult> ManufacturerDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var manufacturer = await _context.Manufacturer
                .Include(m => m.Cars)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.Id == id);
            if (manufacturer == null)
            {
                return NotFound();
            }

            return View(manufacturer);
        }

        // GET: Guest/Cars
        public async Task<IActionResult> Cars(string sortOrder, string searchString)
        {
            ViewData["TypeSortParm"] = String.IsNullOrEmpty(sortOrder) ? "type_desc" : "";
            ViewData["CurrentFilter"] = searchString;
            var carsAppContext = from c in _context.Car select c;

            carsAppContext = _context.Car.Include(c => c.Manufacturer).Include(c => c.Reviews).
                ThenInclude(r => r.Driver);

            if (!String.IsNullOrEmpty(searchString))
            {
                carsAppContext = carsAppContext.Where(c => c.Name.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "type_desc":
                    carsAppContext = carsAppContext.OrderBy(c => c.Type);
                    break;
                default:
                    carsAppContext = carsAppContext.OrderBy(c => c.Manufacturer.Name);
                    break;
            }

            return View(await carsAppContext.AsNoTracking().ToListAsync());
        }

        // GET: Guest/CarDetails/5
        public async Task<IActionResult> CarDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _context.Car
                .Include(c => c.Manufacturer)
                .Include(c => c.Reviews).ThenInclude(r => r.Driver)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.Id == id);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }
    }
}

CarsApp/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CarsApp.Data;
using CarsApp.Models;
using Microsoft.AspNetCore.Authorization;

namespace CarsApp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ReviewsController : Controller
    {
        private readonly CarsAppContext _context;

        public ReviewsController(CarsAppContext context)
        {
            _context = context;
        }

        // GET: Reviews
        public async Task<IActionResult> Index()
        {
            var carsAppContext = _context.Review.Include(r => r.Car).Include(r => r.Driver);
            return View(await carsAppContext.ToListAsync());
        }

        // GET: Reviews/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var review = await _context.Review
                .Include(r => r.Car)
                .Include(r => r.Driver)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (review == null)
            {
                return NotFound();
            }

            return View(review);
        }

        // GET: Reviews/Create
        public IActionResult Create()
        {
            ViewData["CarId"] = new SelectList(_context.Car, "Id", "Name");
            ViewData["DriverId"] = new SelectList(_context.Driver, "Id", "FullName");
            return View();
        }

        // POST: Reviews/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CarId,DriverId,EngineType,EngineSize,FuelConsumption,Description")] Review review)
        {
            if (ModelState.IsValid)
            {
                _context.Add(review);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CarId"] = new SelectList(_context.Car, "Id", "Name", review.CarId);
            ViewData["DriverId"] = new SelectList(_context.Driver, "Id", "FirstName", review.DriverId);
            return View(review);
        }

        // GET: Reviews/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var review = await _context.Review.FindAsync(id);
            if (review == null)
            {
                return NotFound();
            }
            ViewData["CarId"] = new SelectList(_context.Car, "Id", "Name", review.CarId);
            ViewData["DriverId"] = new SelectList(_context.Driver, "Id", "FirstName", review.DriverId);
            return View(review);
        }

        // POST: Reviews/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CarId,DriverId,EngineType,EngineSize,FuelConsumption,Description")] Review review)
        {
            if (id != review.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(review);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReviewExists(review.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CarId"] = new SelectList(_context.Car, "Id", "Name", review.CarId);
            ViewData["DriverId"] = new SelectList(_context.Driver, "Id", "FirstName", review.DriverId);
            return View(review);
        }

        // GET: Reviews/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var review = await _context.Review
                .Include(r => r.Car)
                .Include(r => r.Driver)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (review == null)
            {
                return NotFound();
            }

            return View(review);
        }

        // POST: Reviews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var review = await _context.Review.FindAsync(id);
            _context.Review.Remove(review);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReviewExists(int id)
        {
            return _context.Review.Any(e => e.Id == id);
        }
    }
}

CarsApp/Views/Cars/Create.cshtml
@model CarsApp.Models.Car

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Car</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModelYear" class="control-label"></label>
                <input asp-for="ModelYear" class="form-control" />
                <span asp-validation-for="ModelYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManufacturerId" class="control-label"></label>
                <select asp-for="ManufacturerId" class="form-control" asp-items="ViewBag.ManufacturerId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script type="text/javascript">
        // Add the following code if you want the name of the file appear on select
        $(".custom-file-input").on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });
    </script>
}

CarsApp/Views/Cars/Delete.cshtml
@model CarsApp.Models.Car

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Car</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ModelYear)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ModelYear)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Manufacturer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Manufacturer.Name)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CarsApp/Views/Cars/Details.cshtml
@model CarsApp.Models.Car

@{
    ViewData["Title"] = "Details";
    var photoPath = "~/CarImages/" + (Model.CarPicture ?? "blankImage.png");
}

<h1>Details</h1>

<div>
    <h4>@Html.DisplayFor(model => model.Manufacturer.Name) @Html.DisplayFor(model => model.Name)</h4>
    <hr />
    <img src="@photoPath"
         asp-append-version="true" />

    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ModelYear)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ModelYear)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Manufacturer)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Manufacturer.Name)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Reviews)
        </dt>
        <dd class="col-sm-10">
            <table class="table">
                <tr>
                    <th>Driver</th>
                    <th>Engine Type</th>
                    <th>Engine Size</th>
                </tr>
                @foreach (var item in Model.Reviews)
                {
                    <tr>
                        <td>
                            <a asp-controller="Drivers" asp-action="Details" asp-route-id="@item.Driver.Id">@Html.DisplayFor(modelItem => item.Driver.FullName)</a>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.EngineType)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.EngineSize)
                        </td>
                        <td>
                            <a asp-controller="Reviews" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                            <a asp-controller="Reviews" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                            <a asp-controller="Reviews" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        </td>
                    </tr>
                }
            </table>
        </dd>


    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CarsApp/Views/Cars/Edit.cshtml
@model CarsApp.Models.Car

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Car</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ModelYear" class="control-label"></label>
                <input asp-for="ModelYear" class="form-control" />
                <span asp-validation-for="ModelYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManufacturerId" class="control-label"></label>
                <select asp-for="ManufacturerId" class="form-control" asp-items="ViewBag.ManufacturerId"></select>
                <span asp-validation-for="ManufacturerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>

            <div class="form-group">
                @if (Model.CarPicture == null)
                {
                    <label class="control-label">Picture</label>
                    <input type="file" name="imageUrl" />
                }
                else
                {
                    <label>Chosen picture:</label>
                    <img src="~/CarImages/@Model.CarPicture"
                         height="100" width="100"
                         asp-append-version="true" />
                    <br />
                    <input type="file" name="imageUrl" />
                }
            </div>

        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script type="text/javascript">
        // Add the following code if you want the name of the file appear on select
        $(".custom-file-input").on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });
    </script>
}

CarsApp/Views/Cars/Index.cshtml
@model IEnumerable<CarsApp.Models.Car>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ModelYear)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Manufacturer)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ModelYear)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @if (item.ManufacturerId != null)
                {
                    <a asp-controller="Manufacturers" asp-action="Details" asp-route-id="@item.ManufacturerId"> @Html.DisplayFor(modelItem => item.Manufacturer.Name)</a>
                }
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

CarsApp/Views/Cars/ReviewsByCar.cshtml
@model CarsApp.Models.Car

@{
    ViewData["Title"] = "Car Reviews";
}

<h3>@Html.DisplayFor(model => model.Manufacturer.Name) @Html.DisplayFor(model => model.Name) | Reviews</h3>

<table class="table">
    <thead>
        <tr>
            <th>
                Driver
            </th>
            <th>
                Engine Size
            </th>
            <th>
                Engine Type
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Reviews)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Driver.FullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EngineSize)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EngineType)
                </td>
                <td>
                    <a asp-controller="Driver" asp-action="OthersReview" asp-route-id="@item.Id">Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<div>
    <a asp-controller="Guest" asp-action="CarDetails" asp-route-id="@Model.Id">Go Back</a>
</div>